collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_footprint
    odom_frame_id: odom
    cmd_vel_in_topic: /cmd_vel
    cmd_vel_out_topic: /cmd_vel_safe
    state_topic: /collision_monitor_state
    expected_planner_frequency: 10.0
    transform_tolerance: 0.5
    state_update_rate: 10.0
    source_timeout: 1.0
    stop_pub_timeout: 0.5
    polygons: ["footprint", "stop_zone"]

    footprint:
      type: "polygon"
      action_type: "stop"
      min_points: 3
      points: [1.05, 0.38, 1.05, -0.38, -0.12, -0.38, -0.12, 0.38]
      visualize: true
      enabled: true

    stop_zone:
      type: "polygon"
      action_type: "stop"
      min_points: 3
      points: [1.65, 0.56, 1.65, -0.56, -0.30, -0.56, -0.30, 0.56]
      polygon_pub_topic: "/stop_zone_raw"
      visualize: true
      enabled: true

    observation_sources: ["scan"]
    scan:
      type: scan
      topic: /scan
      enabled: true
