local_costmap:
  local_costmap:
    ros__parameters:
      filters: []
      keepout_filter:
        enabled: false

global_costmap:
  global_costmap:
    ros__parameters:
      filters: []
      keepout_filter:
        enabled: false
