#!/usr/bin/env bash
set -euo pipefail

CAMERA_RTSP_URL="${CAMERA_RTSP_URL:-rtsp://admin:teamcit2024@192.168.1.64:554/Streaming/Channels/101}"
HTTP_PORT="${HTTP_PORT:-8089}"
OUTPUT_FPS="${OUTPUT_FPS:-1}"
JPEG_QUALITY="${JPEG_QUALITY:-6}"
SCALE="${SCALE:-1280:-2}"
PROBESIZE="${PROBESIZE:-32768}"
ANALYZEDURATION="${ANALYZEDURATION:-100000}"
OVERLAY_ENABLED="${OVERLAY_ENABLED:-false}"

echo "[rtsp-cam] stream en http://localhost:${HTTP_PORT}/"

CAMERA_RTSP_URL="$CAMERA_RTSP_URL" \
HTTP_PORT="$HTTP_PORT" \
OUTPUT_FPS="$OUTPUT_FPS" \
JPEG_QUALITY="$JPEG_QUALITY" \
SCALE="$SCALE" \
PROBESIZE="$PROBESIZE" \
ANALYZEDURATION="$ANALYZEDURATION" \
OVERLAY_ENABLED="$OVERLAY_ENABLED" \
python3 "$(dirname "$0")/rtsp_mjpeg_server.py"
